[tool.poetry]
name = "aoc17"
version = "0.1.0"
description = ""
authors = ["Baumann Patrick <pb083@hdm-stuttgart.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
